name: On push to `main`

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          manifest-file: ".github/release-please/manifest.json"
          config-file: ".github/release-please/configuration.prerelease.json"
